version: '3'

services:
  db:
    image: "couchdb"
    ports:
      - 5984:5984
    volumes:
      - db-data:/opt/couchdb/data
    env_file: 
      - .env
  master_scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.master_scheduler
    command: tail -f /dev/null
    env_file: 
      - .env

  dask_worker:
    build:
      context: ./
      dockerfile: Dockerfile.dask_worker
    command: ["dask-worker", "tcp://dask_scheduler:8786"]
    env_file: 
      - .env
    ports:
      - 8790:8786
      - 8791:8787
    shm_size: 2G
    privileged: true

  dask_scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.dask_worker
    command: ["dask-scheduler"]
    env_file: 
      - .env
    ports:
      - 8786:8786
      - 8787:8787

volumes:
  db-data: